### ISSUE TITLE
Issues by 11:59pm tonight

### ISSUE THREAD

**Issue by onzfonz** [chriskith/COMP-129-Individual-Project#1]
Thanks for forking the project!  Just wanted to make sure you also made the three issues on here by 11:59pm, you can make them here.  You can close this issue to once you got the memo.

**Comment by chriskith** [comment]
3 Features/Issues
1. Adding power ups to the game. Powerups such as slowing down the movement speed of the pipes and invincibility which will make the character clip the pipes for 7 seconds. Powerups will be a new class and it will affect the PipeGeneration class. With slowtime, it will affect the pipe movement and that’s located in the PipeGeneration class. Same with invincibility because the collision detection is located in the class. As for the powerups spawning on the map, it should be done in PowerUps class itself. Will have to adjust the pipe spawn rate.
2. Implementing enemies to the game. Other than the pipes as the only obstacles, but stationary enemies that will spawn randomly. This will have the players determine the placement of the bird. For example This will be its own class known as Enemy. It will affect the PipeGeneration. I would need to fix the pipe spawn and adjust the spacing when the pipe spawns. 
3. New bird skins will be implemented. A shop will need to implemented and that would need it’s own GraphicPane. It will need to be added to the menu pane as well. As an in game currency will need to be implemented. The score converter will determine how much in game currency you can receive.

**Comment by onzfonz** [comment]
I just realized that you did not fork the project, so please look at the other issue for what you'll need to do.
